added integration model
brimblehq/brimble pull request #20
Opened 2022-08-20 19:42 UTC by pipethedev

2022-08-20 19:46 UTC, klefcodes requested changes

2022-08-20 19:46 UTC, klefcodes commented on packages/models/integration.ts
> +    name: {
This won't work; Change to. `name: { type: String, enum: Object.values(INTEGRATION_TYPE), required: true }`

2022-08-20 19:47 UTC, pipethedev commented on packages/models/integration.ts
> +    name: {
Alright calm

2022-08-22 16:02 UTC, klefcodes approved these changes

2022-08-22 16:02 UTC, merged